apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "suse-ai-operator.labels" . | nindent 4 }}
  name: {{ include "suse-ai-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "suse-ai-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "suse-ai-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "suse-ai-operator.labels" . | nindent 4 }}
  name: {{ include "suse-ai-operator.fullname" . }}
  namespace: {{ include "suse-ai-operator.extensionsNamespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "suse-ai-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "suse-ai-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
